### ISSUE TITLE
Release ALSA to enable playing from Volumio again

### ISSUE THREAD

**Issue by TommySharpNZ** [Saiyato/volumio-squeezelite-plugin#2]
Hey there.... Was giving this plugin a try and it works really well!
Once I've played some audio via my squeezebox server, how do we "release" it so that someone can play audio again through Volumio?
The only way I can do it at the moment is to stop the plugin.

**Comment by Saiyato** [comment]
That is correct, I have no idea how else to stop the client, it's not the plugin that uses ALSA, but the squeezelite process. So killing the process will release it, the client is not designed to be used in parallel with other software I suppose.

**Comment by marcoc1712** [comment]
Saiyato, just a little suggestion here; 

launching squeezelite with -C x parameters will release the output device after x secs  of silence (please replace x with a valid integer, 1 is perfect). 

That way You could use it with any other player with no wonder of stopping squeezelite process. Obviously, you could then get an error trying to use squeezelite when the sound card is in use by others, so you should do the same in other players too.

**Comment by Saiyato** [comment]
This is a great find! I will see how I can implement this.
