### ISSUE TITLE
Squeezelite plugin settings don't persist

### ISSUE THREAD

**Issue by enomam** [Saiyato/volumio-squeezelite-plugin#7]
I’ve got two Raspberry Pi’s setup with Volumio, an each has the squeezelite plugin installed.
However, no matter what I set the InstanceName to in the settings, the devices keep reporting themselves as “Volumio”, meaning I’ve got two entries with the same name - very hard to differentiate! I can rename them in LMS, but whenever a Volumio device reboots, it updates to the original “Volumio” name.

If I have a look at the squeezelite.service file, as well as config.json, no where is the instance name I chose being set anywhere.

So - how do I change the squeezelite name of my Volumio without having to manually edit the files in /data/plugins/music_service/squeezelite ?

**Comment by lavapies01** [comment]
Hi. Did you ever find a solution to this as I'm having the same problem? Whatever I do I can't change the Squeezelite player name from volumio. Thanks in advance for any help

**Comment by Saiyato** [comment]
Just fixed this, for some reason I remove the template, which resulted in fatal exceptions and null references. In any case, version 1.1.6 doesn't have this problem anymore, I will try to push to the Volumio store tonight.

**Comment by Saiyato** [comment]
Update: you can now install version 1.1.6 from the store (you have to enable test packages on /dev).
Note: in the past when selecting the mixer device you could 'fast swap' between Squeeze & Volumio; now you need to stop the plugin if you want to listen to Volumio sources. I need to come up with a more graceful solution when I plan the AAMPP implementation.

**Comment by lavapies01** [comment]
Big thanks for looking at this and fixing. Look forward to installing new version at the weekend.

**Comment by lavapies01** [comment]
> Just fixed this, for some reason I remove the template, which resulted in fatal exceptions and null references. In any case, version 1.1.6 doesn't have this problem anymore, I will try to push to the Volumio store tonight.

Works perfect, just installed 1.1.6 and player names persist 😀 Thanks again 👍
