### ISSUE TITLE
Installation fails because "/bin/mv: target '/tmp/plugins/squeezelite.zip' is not a directory"

### ISSUE THREAD

**Issue by liamg2187** [Saiyato/volumio-squeezelite-plugin#9]
I cloned the zip file to my raspberry pi running Volumio and then unzipped it. I went into the folder where the package.json is and ran $volumio plugin install as root. It began installing but then failed because it couldn't find a directory. Did I install it wrong? Here's the full error: [https://pastebin.com/6aMLbLhZ](url)

**Comment by Saiyato** [comment]
Hi buddy,

Just to verify, you cloned the zipfile, or the entire repo? This sounds like you cloned the entire repo, after which you MUST delete the zipfile before running `volumio plugin install` as NON-root user :wink:

Please read through this: github.com/saiyato/volumio-plugin-helper
